### ISSUE TITLE
How can i start the server without entering to the ServerManager.exe?

### ISSUE THREAD

**Issue by ghost** [mrphil2105/TF2-Server-Manager#11]
I wanna start automatically the server every time my pc turns on, i know how to do start an app when windows start, but i dont want to make the few clicks in the interface every time my pc turns on, what can i do?

**Comment by DDownHub** [comment]
Create a shortcut that references to the file 'C:\hlserver\steamapps\common\Team Fortress 2 Dedicated Server\srcds.exe'. Name the shortcut an appropriate name,
Right click on the shorcut, select properties,
Set Target to:
C:\hlserver\steamapps\common\Team Fortress 2 Dedicated Server\srcds.exe -console -game tf +sv_pure 1 +map ctf_2fort +maxplayers 24
from https://wiki.teamfortress.com/wiki/Windows_dedicated_server

**Comment by DDownHub** [comment]
btw i recommend turning sv_pure to 0
