### ISSUE TITLE
unable to create port mapping

### ISSUE THREAD

**Issue by BritishColonist69** [mrphil2105/TF2-Server-Manager#13]
i have been able to create servers for me and my friends fine before, however today for no reason i have been getting this error. does anyone have a fix?

Unable to create port mapping, either your router/NAT has port mapping disabled or it is not supported. To fix this issue you might need to make a port forward in your router configuration (find a tutorial for your router online). People
outside of your local network will be unable to join your server without a port mapping/forward. You can disable automatic port mapping in Help > Settings > Network.

**Comment by mrphil2105** [comment]
As the text that I wrote in the message box indicates, you'll have to make a port forward manually. There are plenty of guides out there on the internet that might help you, but keep in mind that every router's config is different.
