### ISSUE TITLE
using maps directly from the workshop?

### ISSUE THREAD

**Issue by BritishColonist69** [mrphil2105/TF2-Server-Manager#14]
i am aware you can already use workshop maps by dropping the file into the maps folder in the server folder, however this means any friends who want to join have to drag and drop the map into their tf2 maps folder aswell.  so I was wondering if it is possible to use workshop maps directly from the workshop, so when a friend joins it says downloading workshop map.

**Comment by beyluta** [comment]
Afaik, Maps are automatically downloaded to the player's local `/maps` folder when joining a server. Check your server settings for an option that enables the download of server assets.
