### ISSUE TITLE
TF2 Server Manager Port Mapping issue

### ISSUE THREAD

**Issue by JohnAllison15** [mrphil2105/TF2-Server-Manager#15]
Got this error when starting server after running updater, think its a port mapping issue. Any ideas on how to fix this? :/

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. An existing connection was forcibly closed by the remote host.

System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host

************ JIT Debugging ************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by pinheadtf2** [comment]
Not the dev, and I'm late but a friend had this issue. What he didn't do is unpack those two DLLs into the same folder as the exe. If that isn't the case, I'm afraid I have no more info. Good luck!
