### ISSUE TITLE
SourceTV hard-coded disabled

### ISSUE THREAD

**Issue by SirBlockles** [mrphil2105/TF2-Server-Manager#18]
I understand that this server manager was written for simple "plug and play" style servers to play with friends, however hard-coding `-nohltv` into the server's launch options is extremely annoying. I just spent an hour helping a friend debug STV where all the settings were correctly applied, but due to launching it through this server manager, it was still disabled.

I understand the approach of simplification, however force-disabling SourceTV when it has to manually be enabled anyway seems ham-fisted and obnoxious to anyone learning how to set it up on their own and not figuring out why it isn't working.

**Comment by mrphil2105** [comment]
I understand your frustration and apologize for the inconvenience that poor decision of mine might have caused. Feel free to clone the repository and recompile the code on your own, without the `-nohltv` parameter.
