### ISSUE TITLE
Console Crash

### ISSUE THREAD

**Issue by FrostCookie8** [mrphil2105/TF2-Server-Manager#19]
So I changed the map to mvm_mannhattan (typed exactly as I typed here) for me and my brother to practice on (max 2 players) but the console (I think that's what the black screen with the white text is called) always crashes. Is this an issue with the player count or something? It crashes too fast for me to read the problem, but it says something about speculars, if those are important. Sorry if that's not enough info, I didn't think anything else would be relevant.

**Comment by Enderman1444** [comment]
maybe cuz u didn't make 32 max players? because that's the minimum required for MVM
