### ISSUE TITLE
Where Has This Project Gone Too? The Answer For Everyone... 

### ISSUE THREAD

**Issue by RoYoshi** [mrphil2105/TF2-Server-Manager#21]
Now many of you may be having some major issues with the server manager but one thing is that the project maybe is still being worked on? It's a maybe, But the Server manager is pretty much outdated and will barely work with hosting a server, the same problem keeps happening over and over again. I feel like the only way to fix this is if it gets back into being worked on! but still the idea of this project is amazing! Just, need to be worked on....

**Comment by mrphil2105** [comment]
This tool is not being updated anymore and I'd rather create a new and improved tool instead, because I am using a different GUI framework now.
