### ISSUE TITLE
This tool is basically dead and it sucks

### ISSUE THREAD

**Issue by 5ix1t** [mrphil2105/TF2-Server-Manager#26]
i used this tool a lot for playing privately with friends and now because of the recent tf2 summer update it completely breaks this tool

so please crazy update this i beg of you

**Comment by mrphil2105** [comment]
Maybe you could provide some additional information about why it does not work?

**Comment by directive-unknown** [comment]
I am looking for a tool like this. Shame that it broke. There's another one called [tf2 server launcher](http://www.github.com/beyluta/tf2-server-launcher) that works on my computer. But it is much simpler than this one. I don't know much about programming, but could you look at that one to fix this one?

**Comment by mrphil2105** [comment]
The other tool is written in an entirely different framework than mine. A framework I actually am not very fond of using. But what could help is more information about the issues you're facing. Try to describe the issues and provide any errors that you're receiving.
