### ISSUE TITLE
App state is 0x202 after update job.

### ISSUE THREAD

**Issue by IdkWhatUsernameToPick** [mrphil2105/TF2-Server-Manager#29]
Whenever I run the updater it comes up with an error message:

 Update state (0x0) unknown, progress: 0.00 (0 / 0)
Error! App '232250' state is 0x202 after update job.
Please use force_install_dir before logon!

**Comment by mrphil2105** [comment]
Please only open issues related to the software itself.
0x202 means you do not have enough disk space left.
