### ISSUE TITLE
Friends cant join, failed after 4 attempts 

### ISSUE THREAD

**Issue by ghost** [mrphil2105/TF2-Server-Manager#3]
When ever my friend tries to join he gets the message failed after 4 attempts, I've tried using ports: 28015, 28016 and 28020 but he gets the same message each time. I can join no problem. I don't know if it's a port forward issue or the firewall is blocking it. Any idea how to fix it? Here's an image of the server manager 
![image](https://user-images.githubusercontent.com/49558201/56035455-2276e800-5d22-11e9-9d32-d6165cb9b60b.png)

**Comment by LazyBugbear18** [comment]
Yap, same thing here, can join myself, but friends cant through ip.(failed after 4 tries)

**Comment by drgamercat** [comment]
same thing here

**Comment by Pecus35** [comment]
BRUH SAYING THE SAME THING HERE DOESNT MAKE IT SOLVED

**Comment by mrnoahfink** [comment]
have you set an automatic port forward on?
