### ISSUE TITLE
Failed after four retries

### ISSUE THREAD

**Issue by Mecrusher** [mrphil2105/TF2-Server-Manager#9]
Hey!

I wanted to make a server for my friends to join onto. When I stumbled apon your server manager, I thought that it would be able to have people connect, with no issues! When I tried to connect to the server from the console that's in game, It wouldn't let me on. But, when I tried joining on with the "Connect" button that's in the server manager, it works! And I know this isn't a issue with port forwarding. And yes, if you were wondering, I tried to connect onto the server with my brothers Pc. From the console, and It failed! Both of us (when connecting from the console), got the exact same message, too.
<Connection failed after 4 retries>

This really made me upset, and I hope you can fix this issue soon.

**Comment by codeoverseer** [comment]
> Hey!
> 
> I wanted to make a server for my friends to join onto. When I stumbled apon your server manager, I thought that it would be able to have people connect, with no issues! When I tried to connect to the server from the console that's in game, It wouldn't let me on. But, when I tried joining on with the "Connect" button that's in the server manager, it works! And I know this isn't a issue with port forwarding. And yes, if you were wondering, I tried to connect onto the server with my brothers Pc. From the console, and It failed! Both of us (when connecting from the console), got the exact same message, too.
> <Connection failed after 4 retries>
> 
> This really made me upset, and I hope you can fix this issue soon.

did u find a solution?
